id: IE1841804
ocr_import_info:
  timestamp: '2023-09-12T06:52:46.203471+00:00'
  batch_id: batch-3e72
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Openpecha
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-22 11:10:45.063590+00:00
last_modified: 2023-09-22 11:10:45.063599+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM247
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM247
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པའི་ཚིག་འགྲེལ་ལེགས་བཤད་རྗེས་འབྲང་།
  languages:
  - bo
  author: ཁལ་ཁ་ངག་དབང་དཔལ་ལྡན།
statistics:
  ocr_word_mean_confidence_index: 0.9628102856848362
  ocr_word_median_confidence_index: 0.9992329
bases:
  I1NLM247_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM247_001
      total_pages: 380
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM247_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9992329
      ocr_word_mean_confidence_index: 0.9628102856848362
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
